version: '2'
catalog:
  name: Fail2Ban
  version: 1.0.0
  description: Fail2Ban IP filter with IP-release WebFrontend
  minimum_rancher_version: v0.63.0
  questions:
    - variable: STORAGE_LOGS_VOLUME 
      label: Logs volume
      description: "Enter path on the host of a volume containing all log files of other containers"
      required: true
      type: string
    - variable: STORAGE_CONFIG_VOLUME 
      label: Config volume
      description: "Enter path on the host of a Volume containing the configuration for fail2ban"
      required: false
      type: string
    - variable: OAUTH_PROVIDER
      label: OAuth Provider
      description: Select one of the supported OAuth providers
      required: true
      type: enum
      options:
        - gitlab
    - variable: OAUTH_PROVIDER_URI
      label: URI of the OAuth provider
      description: Enter the URI of the OAuth provider (e.g. https://git.example.com)
      required: true
      type: string
    - variable: OAUTH_CLIENT
      label: OAuth client key
      description: Enter the OAuth client key
      required: true
      type: string
    - variable: OAUTH_SECRET
      label: OAuth client secret
      description: Enter the OAuth client secret
      required: true
      type: password
    - variable: DOMAIN
      label: Domain of your freeIP WebInterface
      description: If OAuth is enabled enter the domain of the etherpad instance (for Cookie handling)
      required: true
      type: string
    - variable: PROTOCOL
      label: Protocol for your freeIP WebInterface
      description: If OAuth is enabled select the protocol for the Etherpad instance
      required: true
      type: enum
      options:
        - http
        - https
services:
  releaseIP:
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 4444
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
