.catalog:
  name: Let's Encrypt ZAWiW
  version: v0.1
  description: Let's Encrypt for all ZAWiW-domains
  minimum_rancher_version: v0.63.0
  questions:
    - variable: CLOUDFLARE_EMAIL
      label: CloudFlare Email Address
      description: Enter the email address associated with your CloudFlare account.
      type: string
      required: true
    - variable: CLOUDFLARE_KEY
      label: CloudFlare API Key
      description: Enter the Global API Key for your CloudFlare account.
      type: password
      required: true
    - variable: VOLUME_NAME
      label: Volume Name (Optional)
      description: |
        Persistent data can be saved on the host or in a named volume. So type either a path on the host (e.g. /export/maustraining) or the name of the named volume
      required: false
      type: string
