version: '2'
services:
  openldap:
    image: swinkelhofer/openldap
    stdin_open: true
    volumes:
    - ${STORAGE_VOLUME}/ldap:/var/lib/openldap/openldap-data
    environment:
    - LDAP_BASE=${LDAP_BASE}
    - LDAP_ROOT_USER=${LDAP_ROOT_USER}
    - LDAP_ROOT_PW=${LDAP_ROOT_PW}
    tty: true
    labels:
      io.rancher.container.pull_image: always
