version: '2'
catalog:
  name: OpenLDAP
  version: 1.0.0
  description: OpenLDAP Server
  minimum_rancher_version: v0.63.0
  questions:
    - variable: STORAGE_VOLUME 
      label: Storage Volume
      description: |
        Persistent data can be saved on the host or in a named volume. So type either a path on the host (e.g. /export/openldap) or the name of the named volume
      required: false
      type: string
services:
  openldap:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 389
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
