.catalog:
  name: OSTicket
  version: 1.0.0
  description: Ticket System with LDAP-integration
  minimum_rancher_version: v0.63.0
  questions:
    - variable: MAILSERVER_LINK
      label: Link to the mailserver
      description: Enter the name of a mailserver-container (form: Stack/Service)
      required: true
      default: "Postfix/mailserver"
      type: string
    - variable: LDAP_LINK
      label: Link to the LDAP Server
      description: Enter the name of a OpenLDAP-container (form: Stack/Service)
      default: "OpenLDAP/openldap"
      required: true
      type: string
    - variable: STORAGE_VOLUME
      label: Volume Path
      description: |
        Path on the host where the backups should be stored.
      required: true
      type: string
