version: '2'
services:
  wiki:
    image: "registry.zawiw.de:5000/wiki"
    stdin_open: true
  {{- if eq .Values.USE_CONFIG_SIDEKICK "true" }}
    volumes_from:
    - "wiki-config"
  {{- end }}
    volumes:
    - ${STORAGE_VOLUME}:/opt/moin/wiki/data
    tty: true
    labels:
      io.rancher.container.pull_image: always
  {{- if eq .Values.USE_CONFIG_SIDEKICK "true" }}
  wiki-config:
    image: "${CONFIG_SIDEKICK_IMAGE}"
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  {{- end }}
