version: '2'
services:
  {{- if eq .Values.ENABLE_OAUTH "true" }}
  oauth-reverse-proxy:
    image: registry.zawiw.de:5000/swinkelhofer/oauth_reverse_proxy
    environment:
      OAUTH_CLIENT: ${OAUTH_CLIENT}
      OAUTH_SECRET: ${OAUTH_SECRET}
      DOMAIN: ${DOMAIN}
      PROTOCOL: ${PAD_PROTOCOL}
      OAUTH_PROVIDER: ${OAUTH_PROVIDER}
      OAUTH_PROVIDER_URI: ${OAUTH_PROVIDER_URI}
      UPSTREAM_HOSTNAME: admin-landing
      UPSTREAM_PORT: '80'
    stdin_open: true
    tty: true
    links:
    - etherpad:etherpad
    labels:
      io.rancher.container.pull_image: always
  {{- end }}
  admin-landing:
    image: registry.zawiw.de:5000/swinkelhofer/admin-zawiw-de:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      admin-zawiw-de: 'true'
