version: '2'
catalog:
  name: ZAWiW Admin Landing
  version: 1.0.0
  description: Landing page for ZAWiW administrative tasks
  minimum_rancher_version: v0.63.0
  questions:
    - variable: ENABLE_OAUTH
      label: Use OAuth authentification?
      default: false
      type: boolean
    - variable: OAUTH_PROVIDER
      label: Which OAuth provider to use?
      description: Select one of the following OAuth providers
      required: false
      type: enum
      options:
        - gitlab
    - variable: OAUTH_PROVIDER_URI
      label: URI of the OAuth provider
      description: Enter the URI of the OAuth provider (e.g. https://git.example.com)
      required: false
      type: string
    - variable: OAUTH_CLIENT
      label: OAuth client key
      description: Enter the OAuth client key
      required: false
      type: string
    - variable: OAUTH_SECRET
      label: OAuth client secret
      description: Enter the OAuth client secret
      required: false
      type: password
    - variable: DOMAIN
      label: Domain of your AdminLanding instance
      description: If OAuth is enabled enter the domain of the AdminLanding instance (for Cookie handling)
      required: false
      type: string
    - variable: PROTOCOL
      label: Protocol for your AdminLanding instance
      description: If OAuth is enabled select the protocol for the AdminLanding instance
      required: false
      type: enum
      options:
        - http
        - https
services:
  admin-landing:
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000

